
import "bootstrap/dist/css/bootstrap.min.css";

import Navbar from "./components/Navbar";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Navbar />
        <Suspense fallback={<loading />} >
          {children}
        </Suspense>
      </body>
    </html>
  );
}
